# Pod for nginx application
apiVersion: v1
kind: Pod
metadata:
  name: service.nginx-1
  labels:
    appName: service-nginx-1
spec:
  containers:
    - name: nginx
      image: nginx

---
# ClusterIP service for nginx Pod
apiVersion: v1
kind: Service
metadata:
  name: service.nginx-1
spec:
  type: ClusterIP
  selector:
    appName: service-nginx-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
# Debug Pod
apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
    - name: debug
      image: rkalluru/debug

---