apiVersion: v1
kind: pod
metadata:
  name: service.nginx-1
  labels:
    appName: service-nginx-1
spec:
 containers:
   -name: nginx
   image: nginx

---
apiVersion: v1
kind: service
metadata:
  name: service.nginx-1
spec:
  type: Cluster IP
  selector:
    appName: service-nginx-1
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
---
apiVersion: v1
kind: pod
metadata:
  name: debug
spec:
  containers:
    -name: debug
    image: rkalluru/debug

---

apiVersion: v1
kind: service
metadata:
  name: service.nginx-np
spec:
  type: NodePort
  selector:
    appName: service-nginx-1
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
---
apiVersion: v1
kind: service
metadata:
  name: service.nginx-lb
spec:
  type: LoadBalancer
  selector:
    appName: service-nginx-1
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
---
apiVersion: v1
kind: service
metadata:
  name: my-google.com
spec:
  type: ExternalName
  externalName: www.google.com





