apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc
spec:
  containers:
    - name: debug-container
      image: rkalluru/debug
      volumeMounts:
        - mountPath: /app
          name: app-volume
          volumes:
            - name: app-volume
              persistentVolumeClaim:
                claimName: my-pvc
